#!/bin/bash

eval "export $(egrep -z DBUS_SESSION_BUS_ADDRESS /proc/$(pgrep -u $LOGNAME gnome-session)/environ)"; DISPLAY=:0.0 XAUTHORITY=~/.Xauthority notify-send "Air Conditioner" "Warning! The cup is probaby full."
